[versions]
# Define the dependency versions
activityCompose = "1.13.0"
appcompat = "1.7.1"
lifecycleRuntimeKtx = "2.10.0"
material = "1.14.0"
minSdk = "26"
targetSdk = "37"
compileSdk = "37"

androidx-activity-compose = "1.13.0"
androidx-compose-bom = "2026.05.01"
androidx-core-ktx = "1.18.0"
androidx-lifecycle-runtime-ktx = "2.10.0"
androidx-lifecycle-runtime-compose = "2.10.0"
androidx-navigation-compose = "2.9.8"
paging = "3.5.0"
paging-compose = "3.5.0"
compose-constraint-layout = "1.1.1"
coroutines = "1.11.0"
espresso = "3.5.1"
gradle-plugin = "9.2.1"
androidBuildTools = "9.2.1"
koin = "4.2.2"
junit = "4.13.2"
junit5 = "6.1.0"
junit5-compose = "2.0.1"
android-test-runner = "1.7.0"
junit5-android-test-core = "2.0.1"
junit5-android-test-runner = "2.0.1"
assertj = "3.27.7"
kotlin = "2.4.0"
ksp = "2.3.8"
kotlinx-serialization-json = "1.11.0"
kover = "0.9.8"
ktlint = "11.0.0"
ktlint-plugin = "14.2.0"
mockk = "1.14.11"
room = "2.8.4"
test-rules = "1.5.0"
text-ext = "1.1.5"
retrofit = "3.0.0"
retrofit2-kotlinx-serialization-converter = "1.0.0"
glide = "5.0.7"
glide-compose = "1.0.0-beta09"
landscapist = "2.9.8"
lottie-compose = "6.7.1"
secrets = "2.0.1"
junitKtx = "1.3.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "androidBuildTools" }

androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle-runtime-ktx" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle-runtime-compose" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation-compose" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation-compose" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation-compose" }

androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" } # kapt
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }

junit = { module = "junit:junit", version.ref = "junit" }
junit5 = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit5-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
junit5-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit5" }
junit5-android-compose = { module = "de.mannodermaus.junit5:android-test-compose", version.ref = "junit5-compose" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "android-test-runner" }
junit5-android-test-core = { module = "de.mannodermaus.junit5:android-test-core", version.ref = "junit5-android-test-core" }
junit5-android-test-runner = { module = "de.mannodermaus.junit5:android-test-runner", version.ref = "junit5-android-test-runner" }

androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-material = { module = "androidx.compose.material3:material3" }
androidx-compose-ui-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-viewbinding = { module = "androidx.compose.ui:ui-viewbinding" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-constraint-layout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "compose-constraint-layout" }

androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging-compose" }
androidx-paging-test = { module = "androidx.paging:paging-testing", version.ref = "paging" }


kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }

material = { module = "com.google.android.material:material", version.ref = "material" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-agent-jvm = { module = "io.mockk:mockk-agent-jvm", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
ktlint-gradle = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint" }

# Lottie
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie-compose" }

# Retrofit
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit2-kotlinx-serialization-converter = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2-kotlinx-serialization-converter" }
moshi-converter = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
gson-converter = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }

glide = { module = "com.github.bumptech.glide:glide", name = "glide", version.ref = "glide" }
glide-compose = { module = "com.github.bumptech.glide:compose", name = "glide-compose", version.ref = "glide-compose" }

landscapist-glide = { module = "com.github.skydoves:landscapist-glide", name = "landscapist-glide", version.ref = "landscapist" }
androidx-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junitKtx" }


[bundles]
# Define bundles/groups of libraries
room = ["androidx-room-ktx", "androidx-room-runtime"]
coroutines = ["kotlinx-coroutines-core", "kotlinx-coroutines-android"]

[plugins]
android-application = { id = "com.android.application", version.ref = "gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kover-plugin = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "gradle-plugin" }
secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secrets" }
secrets-classpath = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin:secrets-gradle-plugin", version.ref = "secrets" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-plugin" }